window.GameModules = window.GameModules || {};
window.GameModules.equipment = (() => {
  const KEY = 'arcane-equipment-v1';
  const ICON_SHEETS = { gold:'./assets/generated/equipment-icons-gold-sheet.119ccbff.webp', unique:'./assets/generated/equipment-icons-unique-sheet.0332595f.webp', setPaladin:'./assets/generated/equipment-icons-set-paladin-sheet.d6ae3f39.webp', setMage:'./assets/generated/equipment-icons-set-mage-sheet.d2792467.webp', setRanger:'./assets/generated/equipment-icons-set-ranger-sheet.9fe29e3a.webp', setSaintess:'./assets/generated/equipment-icons-set-saintess-sheet.908e5cd0.webp' };
  const SLOTS = ['weapon','helm','chest','amulet','ring','boots'];
  const SLOT_CN = { weapon:'武器', helm:'头盔', chest:'胸甲', amulet:'项链', ring:'戒指', boots:'靴子' };
  const CLS_CN = { paladin:'圣骑士', mage:'大魔法师', ranger:'游侠', lewdSaintess:'淫靡圣女' };
  const RES = ['physical','fire','frost','arcane','holy','shadow','lust'];
  const RES_CN = { physical:'物理', fire:'火焰', frost:'霜寒', arcane:'奥术', holy:'神圣', shadow:'暗影', lust:'欲望', all:'全属性' };
  const GOLD = [
    ['gold-sun-blade','耀金切割者','weapon',{damage:.16,atkSpeed:.04},{fire:.08,holy:.06}],['gold-meteor-staff','陨星金杖','weapon',{damage:.14,range:.08},{fire:.1,arcane:.04}],['gold-hawk-bow','猎鹰金弓','weapon',{atkSpeed:.1,range:.1},{physical:.08}],['gold-crystal-mace','晶核权杖','weapon',{damage:.12,pickup:.08},{arcane:.08,holy:.04}],['gold-dragon-axe','龙纹战斧','weapon',{damage:.2,move:-.03},{fire:.12}],['gold-moon-dagger','月辉短刃','weapon',{atkSpeed:.14,crit:.05},{frost:.07,shadow:.05}],
    ['gold-ward-crown','守望金冠','helm',{hp:.1,armor:.04},{holy:.08,arcane:.04}],['gold-flame-visor','烬火面甲','helm',{damage:.07,hp:.06},{fire:.12}],['gold-frost-hood','霜纹兜帽','helm',{cooldown:.05,range:.04},{frost:.12}],['gold-stone-helm','岩芯重盔','helm',{hp:.16,armor:.06},{physical:.12}],['gold-void-mask','虚金假面','helm',{damage:.08,pickup:.06},{shadow:.1,arcane:.04}],['gold-rose-veil','蔷薇金纱','helm',{hp:.08,regen:.04},{lust:.1,holy:.04}],
    ['gold-sun-plate','太阳镀层甲','chest',{hp:.18,armor:.06},{holy:.08,fire:.06}],['gold-ember-robe','余烬法袍','chest',{damage:.09,cooldown:.04},{fire:.1,arcane:.04}],['gold-hunter-leather','金线猎装','chest',{move:.08,atkSpeed:.06},{physical:.08,frost:.04}],['gold-deep-carapace','深金壳甲','chest',{hp:.22,move:-.04},{physical:.14}],['gold-mist-robe','迷雾长袍','chest',{range:.08,pickup:.1},{shadow:.1}],['gold-vessel-dress','圣器礼服','chest',{hp:.14,regen:.06},{lust:.12}],
    ['gold-dawn-amulet','黎明护符','amulet',{damage:.08,cooldown:.05},{holy:.1}],['gold-arcane-core','秘法金核','amulet',{range:.1,pickup:.12},{arcane:.12}],['gold-fire-heart','熔火心坠','amulet',{damage:.11,hp:.05},{fire:.12}],['gold-ice-tear','冰月泪滴','amulet',{cooldown:.06,move:.04},{frost:.12}],['gold-bone-charm','骸骨金坠','amulet',{armor:.05,hp:.1},{physical:.1,shadow:.04}],['gold-rose-heart','蔷薇心坠','amulet',{regen:.08,pickup:.08},{lust:.12}],
    ['gold-signet-fury','狂怒金戒','ring',{damage:.1,atkSpeed:.05},{fire:.06}],['gold-signet-focus','专注金戒','ring',{cooldown:.08,range:.04},{arcane:.08}],['gold-signet-guard','坚守金戒','ring',{hp:.1,armor:.04},{physical:.08,holy:.04}],['gold-signet-moon','月影金戒','ring',{move:.06,crit:.04},{frost:.08,shadow:.04}],['gold-signet-greed','拾荒金戒','ring',{pickup:.18,gold:.12},{shadow:.06}],['gold-signet-rose','玫瑰金戒','ring',{regen:.06,hp:.08},{lust:.1}],
    ['gold-sun-greaves','日铸胫甲','boots',{move:.08,hp:.06},{holy:.06,fire:.04}],['gold-wind-boots','疾风金靴','boots',{move:.14,atkSpeed:.04},{physical:.06}],['gold-frost-steps','霜踏长靴','boots',{move:.08,cooldown:.04},{frost:.1}],['gold-void-steps','虚空行靴','boots',{move:.1,range:.05},{shadow:.08,arcane:.04}],['gold-stone-sabaton','岩金战靴','boots',{hp:.12,armor:.04},{physical:.1}],['gold-rose-slippers','蔷薇软靴','boots',{move:.06,regen:.06},{lust:.1}],
  ];
  const UNIQUES = [
    ['unique-void-lantern','暗金·虚空提灯','amulet',{damage:.12,pickup:.18},{shadow:.16,arcane:.08},'每 18 秒吸入附近经验与金币，并使下一次升级选项品质提高。'],['unique-dragon-heart','暗金·龙心余烬','chest',{hp:.2,damage:.1},{fire:.22},'受到生命上限 20% 以上伤害时爆发火环。'],['unique-moon-crown','暗金·霜月王冠','helm',{cooldown:.08,range:.08},{frost:.2},'冻结弹幕命中你时转化为寒月护盾。'],['unique-saint-nail','暗金·圣钉战槌','weapon',{damage:.22,atkSpeed:-.04},{holy:.16},'击杀精英后短暂强化光环伤害。'],['unique-thunder-bow','暗金·雷鸣长弓','weapon',{atkSpeed:.16,range:.14},{arcane:.12,physical:.08},'远程攻击周期性链向高威胁目标。'],['unique-blood-plate','暗金·血契重甲','chest',{hp:.26,armor:.08},{physical:.14,shadow:.1},'低生命时获得吸血反击。'],['unique-clock-gloves','暗金·逆时针环','ring',{cooldown:.12,atkSpeed:.08},{arcane:.14},'拾取 Boss 宝箱后强化冷却节奏。'],['unique-greed-boots','暗金·贪婪旅靴','boots',{move:.12,gold:.28},{shadow:.12},'无尽首个 Boss 额外掉落判定。'],['unique-rose-mirror','暗金·蔷薇镜','amulet',{hp:.14,regen:.1},{lust:.18,holy:.06},'承受属性伤害后储存为反击喷溅。'],['unique-abyss-mask','暗金·深渊假面','helm',{damage:.18,crit:.06},{shadow:.2},'自动攻击优先锁定精英。'],['unique-golem-soul','暗金·巨像魂核','ring',{hp:.2,armor:.06},{physical:.18},'站立时获得岩盾。'],['unique-star-tome','暗金·星陨秘典','weapon',{damage:.18,range:.16},{arcane:.18},'飞弹穿透后召唤小陨星。'],['unique-demon-horn','暗金·魔王断角','helm',{damage:.16,hp:.12},{fire:.12,shadow:.12},'Boss 战中伤害提升，但承压更高。'],['unique-pale-ring','暗金·苍白轮戒','ring',{cooldown:.1,move:.08},{frost:.14,shadow:.08},'受击后短暂相位化。'],['unique-faith-boots','暗金·朝圣者遗步','boots',{move:.08,regen:.08},{holy:.16},'移动留下治疗圣痕。'],['unique-hunt-quiver','暗金·无尽箭匣','amulet',{atkSpeed:.12,range:.1},{physical:.14},'投射物有概率复制一次。'],['unique-plague-bell','暗金·瘟疫铃','weapon',{range:.12,cooldown:.06},{shadow:.14,lust:.06},'精英死亡留下腐蚀领域。'],['unique-sun-shield','暗金·太阳残盾','chest',{hp:.18,armor:.1},{holy:.18,fire:.08},'护盾破裂时清除周围弹幕。'],
  ];
  const SET_FAMILIES = [
    ['paladin','aureate-guardian','辉金守护','setPaladin',{hp:.08,armor:.03,holy:.06}],['paladin','thorn-bulwark','荆棘壁垒','setPaladin',{hp:.1,physical:.06,fire:.04}],['paladin','dawn-judgment','黎明审判','setPaladin',{damage:.07,range:.04,holy:.06}],
    ['mage','astral-missile','星界飞弹','setMage',{damage:.08,arcane:.06,range:.05}],['mage','ember-meteor','余烬陨星','setMage',{damage:.09,fire:.07,cooldown:.03}],['mage','storm-sigil','风暴符印','setMage',{atkSpeed:.06,arcane:.05,cooldown:.04}],
    ['ranger','cyclone-axe','旋风飞斧','setRanger',{atkSpeed:.07,physical:.06,range:.04}],['ranger','moon-hunter','月影猎手','setRanger',{crit:.05,frost:.06,move:.04}],['ranger','venom-shadow','毒影伏击','setRanger',{atkSpeed:.05,shadow:.06,move:.05}],
    ['lewdSaintess','crimson-vessel','绯红圣器','setSaintess',{hp:.1,lust:.07,regen:.04}],['lewdSaintess','violet-hymn','紫罗兰圣歌','setSaintess',{range:.06,holy:.05,lust:.05}],['lewdSaintess','rose-mirror','蔷薇镜像','setSaintess',{damage:.06,lust:.06,shadow:.04}],
  ];
  const pieceNames = { weapon:'武器', helm:'冠冕', chest:'衣甲', amulet:'坠饰', ring:'戒环', boots:'足具' };
  const GOLD_ICONS = { weapon:[0,1,2,3,4,5], helm:[12,13,14,15,16,17], chest:[18,19,20,21,22,23], amulet:[28,29,30,31,32,33], ring:[24,25,26,27,34,35], boots:[27,28,29,24,25,26] };
  const UNIQUE_ICONS = { 'unique-void-lantern':3, 'unique-dragon-heart':1, 'unique-moon-crown':2, 'unique-saint-nail':11, 'unique-thunder-bow':5, 'unique-blood-plate':4, 'unique-clock-gloves':10, 'unique-greed-boots':8, 'unique-rose-mirror':3, 'unique-abyss-mask':6, 'unique-golem-soul':9, 'unique-star-tome':7, 'unique-demon-horn':6, 'unique-pale-ring':3, 'unique-faith-boots':8, 'unique-hunt-quiver':5, 'unique-plague-bell':7, 'unique-sun-shield':9 };
  const setIconIndex = (familyIndex, slot) => { const col = (familyIndex % 3) * 2 + (slot === 'amulet' || slot === 'boots' ? 1 : 0); const row = { weapon:0, helm:1, chest:2, ring:5, amulet:5, boots:4 }[slot] || 0; return row * 6 + col; };
  const toItem = (r, sheet, i) => ({ baseId:r[0], name:r[1], rarity:sheet, slot:r[2], stats:r[3], resists:r[4], effect:r[5]||'', icon:{sheet:ICON_SHEETS[sheet], index:i} });
  const gold = GOLD.map((r,i)=>toItem(r,'gold',GOLD_ICONS[r[2]][i%6])), uniques = UNIQUES.map((r,i)=>toItem(r,'unique',UNIQUE_ICONS[r[0]] ?? i));
  const sets = SET_FAMILIES.flatMap((f,fi)=>SLOTS.map((slot)=>({ baseId:`set-${f[1]}-${slot}`, name:`${f[2]}·${pieceNames[slot]}`, rarity:'set', class:f[0], setId:f[1], setName:f[2], slot, stats:{...Object.fromEntries(Object.entries(f[4]).filter(([k])=>!RES.includes(k))), [slot==='weapon'?'damage':slot==='boots'?'move':slot==='ring'?'atkSpeed':slot==='amulet'?'range':'hp']:.06}, resists:Object.fromEntries(Object.entries(f[4]).filter(([k])=>RES.includes(k))), icon:{sheet:ICON_SHEETS[f[3]], index:setIconIndex(fi, slot)} })));
  const all = [...gold,...uniques,...sets];
  let meta = { items:[], equipped:{}, dust:0 }, ready = false;
  const clone = v => JSON.parse(JSON.stringify(v));
  async function kvGet(k){try{return (await window.dzmm.kv.get(k))?.value??null}catch(_){try{let r=localStorage.getItem(k);return r?JSON.parse(r):null}catch(_){return null}}}
  async function kvPut(k,v){try{await window.dzmm.kv.put(k,v)}catch(_){try{localStorage.setItem(k,JSON.stringify(v))}catch(_){}}}
  function normalize(d){let base={items:[],equipped:{},dust:0}; if(!d||typeof d!=='object')return base; base.items=Array.isArray(d.items)?d.items.filter(x=>x&&x.uid&&x.baseId).slice(0,160):[]; base.equipped=d.equipped&&typeof d.equipped==='object'?d.equipped:{}; base.dust=Math.max(0,Math.floor(Number(d.dust)||0)); return base;}
  async function init(){if(ready)return meta; meta=normalize(await kvGet(KEY)); ready=true; return meta;}
  async function save(){await kvPut(KEY,meta)}
  function baseById(id){return all.find(x=>x.baseId===id)}
  function hydrate(it){let b=baseById(it.baseId); return b?{...clone(b),...it, stats:scaleMap(b.stats,it.level), resists:scaleMap(b.resists,it.level)}:it}
  function scaleMap(m,lv=1){let s=1+Math.max(0,lv-1)*.018,o={}; for(const [k,v] of Object.entries(m||{}))o[k]=Math.round(v*s*1000)/1000; return o}
  function rollDrop(cls,bossKills=1,layer=0){let r=Math.random(),pool=r<.08+layer*.004?uniques:r<.28+layer*.006?sets.filter(x=>!x.class||x.class===cls):gold,b=pool[Math.floor(Math.random()*pool.length)],level=Math.max(1,bossKills+layer*2); return {...clone(b), uid:`eq${Date.now().toString(36)}${Math.random().toString(36).slice(2,7)}`, baseId:b.baseId, level, corrupted:true, source:`Boss ${bossKills}`, stats:scaleMap(b.stats,level), resists:scaleMap(b.resists,level)} }
  async function addItem(item){await init(); let clean={uid:item.uid,baseId:item.baseId,level:item.level||1,source:item.source||'',corrupted:false}; meta.items.unshift(clean); meta.items=meta.items.slice(0,160); await save(); return clean}
  function equippedMap(cls){meta.equipped[cls]=meta.equipped[cls]||{}; return meta.equipped[cls]}
  async function equip(uid,cls){await init(); let it=hydrate(meta.items.find(x=>x.uid===uid)); if(!it||it.corrupted||it.class&&it.class!==cls)return false; equippedMap(cls)[it.slot]=uid; await save(); return true}
  async function unequip(slot,cls){await init(); delete equippedMap(cls)[slot]; await save(); return true}
  function equippedItems(cls){let eq=equippedMap(cls); return SLOTS.map(s=>meta.items.find(x=>x.uid===eq[s])).filter(Boolean).map(hydrate)}
  function stats(cls){let out={resists:{},sets:{},allRes:0,attrCapBonus:0,bossAttrCut:0,eliteAttrCut:0,shieldAttrBlock:0}; for(const it of equippedItems(cls)){for(const [k,v] of Object.entries(it.stats||{}))out[k]=(out[k]||0)+v; for(const [k,v] of Object.entries(it.resists||{}))out.resists[k]=(out.resists[k]||0)+v; if(it.setId)out.sets[it.setId]=(out.sets[it.setId]||0)+1} for(const n of Object.values(out.sets)){if(n>=2)out.allRes+=.06;if(n>=4){out.bossAttrCut+=.1;out.eliteAttrCut+=.08}if(n>=6){out.shieldAttrBlock+=.35;out.attrCapBonus+=.1}} if(equippedItems(cls).some(x=>x.rarity==='unique'))out.attrCapBonus+=.05; return out}
  function pct(v){return `${v>=0?'+':''}${Math.round(v*100)}%`}
  function itemText(it){let s=[]; for(const [k,v] of Object.entries(it.stats||{}))s.push(`${{hp:'生命',damage:'伤害',armor:'护甲',move:'移速',cooldown:'冷却',atkSpeed:'攻速',range:'范围',pickup:'拾取',gold:'金币',regen:'回复',crit:'暴击'}[k]||k} ${pct(v)}`); for(const [k,v] of Object.entries(it.resists||{}))s.push(`${RES_CN[k]||k}抗性 ${pct(v)}`); return s.join(' / ')}
  function iconHtml(it){let i=it.icon?.index||0,x=i%6,y=Math.floor(i/6);return `<span class="eqIcon" style="background-image:url('${it.icon?.sheet||''}');background-position:${x*20}% ${y*20}%"></span>`}
  function data(){return meta}
  return { init, save, data, SLOTS, SLOT_CN, CLS_CN, RES_CN, all, rollDrop, addItem, equip, unequip, equippedItems, stats, hydrate, itemText, iconHtml };
})();
window.Equipment = window.GameModules.equipment;
